""""Add_message_deletion_functionality"

Revision ID: 8bbd2721ee16
Revises: 20260226_0001
Create Date: 2026-03-28 01:47:16.188736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbd2721ee16'
down_revision: Union[str, None] = '20260226_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_deletions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deletions_message_id'), 'message_deletions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_deletions_user_id'), 'message_deletions', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('deleted_for_everyone', sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET deleted_for_everyone = false WHERE deleted_for_everyone IS NULL")
    op.alter_column('messages', 'deleted_for_everyone', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_for_everyone')
    op.drop_index(op.f('ix_message_deletions_user_id'), table_name='message_deletions')
    op.drop_index(op.f('ix_message_deletions_message_id'), table_name='message_deletions')
    op.drop_table('message_deletions')
    # ### end Alembic commands ###
